# Generated by Django 5.1 on 2024-08-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_rename_user_users_fikr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promocode', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.users')),
            ],
            options={
                'db_table': 'promocodes',
            },
        ),
    ]
