# Generated by Django 5.1 on 2024-08-09 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_alter_fikr_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikr',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 17, 21, 57, 208363, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddConstraint(
            model_name='fikr',
            constraint=models.CheckConstraint(condition=models.Q(('mark__gte', 1), ('mark__lte', 5)), name='fikr_mark_check'),
        ),
    ]
