# Generated by Django 5.1 on 2024-08-09 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0013_alter_fikr_created_at_alter_promocode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikr',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 19, 1, 37, 717199, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
