# Generated by Django 5.1 on 2024-08-09 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0014_alter_fikr_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikr',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 14, 3, 8, 186209, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
