# Generated by Django 5.1.1 on 2024-09-12 10:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='NOMI')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Lavozimlar',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='NOMI')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'filial',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='USERNAME')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='TELEFON RAQAM')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='TELEGRAM ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.SH')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('code', models.CharField(max_length=3, verbose_name='MAXSUS KOD')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.department', verbose_name='LAVOZIM')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.filial', verbose_name='FILIAL')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='DepartmentFilial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.department', verbose_name='LAVOZIM')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.filial', verbose_name='FILIAL')),
            ],
            options={
                'verbose_name': 'RankFilial',
                'verbose_name_plural': 'Filial-Lavozim',
                'db_table': 'department_filial',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promocode', models.CharField(max_length=50, unique=True, verbose_name='PROMO KOD')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='YARATILGAN VAQT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.users', verbose_name='PROMO KOD EGASI')),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo kodlar',
                'db_table': 'promocodes',
            },
        ),
        migrations.CreateModel(
            name='Fikr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True, verbose_name='IZOH')),
                ('mark', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='BAHO')),
                ('employee_code', models.IntegerField(null=True, verbose_name='XODIM KODI')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='BAHOLANGAN VAQT')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.department', verbose_name='LAVOZIM')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.filial', verbose_name='FILIAL')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.users', verbose_name='BAHOLAGAN SHAXS')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Bildirilgan fikrlar',
                'db_table': 'fikr',
                'constraints': [models.CheckConstraint(condition=models.Q(('mark__gte', 1), ('mark__lte', 5)), name='fikr_mark_check')],
            },
        ),
    ]
