# Generated by Django 5.1.1 on 2024-09-09 06:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Lavozimlar',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'filial',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.department')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.filial')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='DepartmentFilial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.department')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.filial')),
            ],
            options={
                'verbose_name': 'RankFilial',
                'verbose_name_plural': 'Filial-Lavozim',
                'db_table': 'department_filial',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promocode', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.users')),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo kodlar',
                'db_table': 'promocodes',
            },
        ),
        migrations.CreateModel(
            name='Fikr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('mark', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('employee_code', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.department')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.filial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.users')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Bildirilgan fikrlar',
                'db_table': 'fikr',
                'constraints': [models.CheckConstraint(condition=models.Q(('mark__gte', 1), ('mark__lte', 5)), name='fikr_mark_check')],
            },
        ),
    ]
