# Generated by Django 5.1 on 2024-08-09 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFilial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.department')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.filial')),
            ],
            options={
                'db_table': 'department_filial',
            },
        ),
    ]
