# Generated by Django 5.1 on 2024-08-09 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_departmentfilial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.department')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.filial')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
