# Generated by Django 5.1 on 2024-08-09 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikr',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
