# Generated by Django 5.1 on 2024-08-09 12:40

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0012_alter_fikr_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikr',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 17, 40, 15, 318078, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
