# Generated by Django 5.1 on 2024-08-13 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0015_alter_fikr_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fikr',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 6, 0, 51, 126593, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
