# Generated by Django 5.1 on 2024-08-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0017_alter_fikr_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Rank', 'verbose_name_plural': 'Lavozimlar'},
        ),
        migrations.AlterModelOptions(
            name='departmentfilial',
            options={'verbose_name': 'RankFilial', 'verbose_name_plural': 'Filial-Lavozim'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='fikr',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Bildirilgan fikrlar'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Promo code', 'verbose_name_plural': 'Promo kodlar'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
